# These are supported funding model platforms

# Uncomment and replace with your actual usernames/URLs to enable funding buttons

# GitHub Sponsors
# github: [username1, username2]

# Patreon
# patreon: username

# Open Collective
# open_collective: project-name

# Ko-fi
# ko_fi: username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: username

# IssueHunt
# issuehunt: username

# Custom funding URLs (up to 4)
# custom: ["https://example.com/sponsor", "https://paypal.me/username"]
